//AUTH TYPES.................
export const CHECKAUTH = "CHECKAUTH";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const AUTH_FAIL = "AUTH_FAIL";
export const CLEARAUTH = "CLEARAUTH";
export const FORGOTPASSWORDRESETLINKSUCCESS = "FORGOTPASSWORDRESETLINKSUCCESS";
export const CLEARRESETLINK = "CLEARRESETLINK";
export const RESETPASSWORDSUCCESS = "RESETPASSWORDSUCCESS";
export const CLEARRESETPASSWORDSTATUS = "CLEARRESETPASSWORDSTATUS";


//ERROR TYPES.....................
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const CLEARALL = "CLEARALL";



//PROFILE TYPES............
export const GETPROFILEDATA = "GETPROFILEDATA";
export const UPDATEPROFILEDATA = "UPDATEPROFILEDATA";
export const CLEARPROFILEUPDATESTATUS = "CLEARPROFILEUPDATESTATUS";
export const CHANGEPASSWORDSUCCESS = "CHANGEPASSWORDSUCCESS";
export const CLEARCHANGEPASSWORDSTATUS = "CLEARCHANGEPASSWORDSTATUS";

export const PROFILE_UPDATE_FAILED = "PROFILE_UPDATE_FAILED";

//CONTACT TYPES..................
export const GETCONTACTLISTSUCCESS = "GETCONTACTLISTSUCCESS";
export const GETCONTACTCAMPAIGNTYPE = "GETCONTACTCAMPAINTYPE";
export const CREATECONTACTSUCCESS = "CREATECONTACTSUCCESS";
export const CLEARCREATECONTACTSTATUS = "CLEARCREATECONTACTSTATUS";
export const VIEWCONTACT = "VIEWCONTACT";
export const CLEARVIEWCONTACT = "CLEARVIEWCONTACT";
export const UPDATECONTACTSUCCESS = "UPDATECONTACTSUCCESS";
export const DELETECONTACTSUCCESS = "DELETECONTACTSUCCESS";
export const CLEARDELETECONTACTSTATUS = "CLEARDELETECONTACTSTATUS";
export const FEEDBACKSTATUS = "FEEDBACKSTATUS";
export const CLEARFEEDBACKSTATUS = "CLEARFEEDBACKSTATUS";
export const CAMPAIGNDOWNLOADSTATUS = "CAMPAIGNDOWNLOADSTATUS";
export const CLEARCAMPAIGNDOWNLOADSTATUS = "CLEARCAMPAIGNDOWNLOADSTATUS";
export const CREATEREMINDERSTATUS = "CREATEREMINDERSTATUS";
export const CLEARCREATEREMINDERSTATUS = "CLEARCREATEREMINDERSTATUS";
export const DOWNLOADCAMPAIGNLIST = "DOWNLOADCAMPAIGNLIST";
export const CLEARDOWNLOADCAMPAIGNLIST = "CLEARDOWNLOADCAMPAIGNLIST";

//APPOINTMENT TYPES...............
export const GETAPPOINTMENTSUCCESS = "GETAPPOINTMENTSUCCESS";
export const SEARCHCONTACTAPPOINTMENTSUCCESS = "SEARCHCONTACTAPPOINTMENTSUCCESS";
export const CLEARSEARCHCONTACTAPPOINTMENT = "CLEARSEARCHCONTACTAPPOINTMENT";
export const CREATEAPPOINTMENTSUCCESS = "CREATEAPPOINTMENTSUCCESS";
export const CLEARCREATEAPPOINTMENTSUCCESS = "CLEARCREATEAPPOINTMENTSUCCESS";
export const EDITAPPOINTMENTSUCCESS = "EDITAPPOINTMENTSUCCESS";
export const CLEAREDITAPPOINTMENTSUCCESS = "CLEAREDITAPPOINTMENTSUCCESS";
export const DELETEAPPOINTMENTSUCCESS = "DELETEAPPOINTMENTSUCCESS";
export const CLEARDELETEAPPOINTMENTSUCCESS = "CLEARDELETEAPPOINTMENTSUCCESS";














