export const USER = {
    firstName: null,
    lastName: null,
    userName: null,
    email: null,
    picture: null,
    oncall1: null,
    dop_phone: null,
    mobileNumber: null,
    alternatePhone: null,
    timeZone: null,
    street: null,
    suite: null,
    state: null,
    city: null,
    pin: null,
    birthDate: null,
    industry: null,
    companyName: null,
    rrpLink: null,
  }